### ISSUE TITLE
Clicking on the "Autofill Objectives using AI"-button should show a text, that the process started

### ISSUE THREAD

**Issue by Wunderiro** [RizeCrime/Rize-Project-Planner#2]
After clicking on the button "Autofill Objectives using AI", it seems, as nothing much is happening.
As the focus is on the clicked button, the loading icon on the side does not indicate enough, that the generating process started.
Users might get the idea, that it did not work and leave the page, before the objectives are generated.

side note:
The "Generation Uses:"-counter gets increased, even if no objectives were generated (e.g. when leaving page to eraly).

**Comment by RizeCrime** [comment]
implemented in v0.1.5
